sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start createing an image with dockerfile"
    - docker build -t cxz/docker-app -f Dockerfile.dev .

script:
    - docker run -e CI=true cxz/docker-app npm run test -- --coverage

after_success:
    - echo "Test Success"
